name: taska_ui
description: My Taska UI package
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0
  flutter_lints: ^2.0.0

flutter:

  # uses-material-design: true

  # # To add assets to your application, add an assets section, like this:
  # assets:
  #   - static/images/
  #   - static/images/svg/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Urbanist
      fonts:
        - asset: static/fonts/urbanist/Urbanist-Light.ttf
        - asset: static/fonts/urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: static/fonts/urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: static/fonts/urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: static/fonts/urbanist/Urbanist-Bold.ttf
          weight: 700